version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:${WEB_PORT}
    volumes:
      - .:/app
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
